ARG NODE_VERSION=22

FROM node:${NODE_VERSION}-alpine

ENV NODE_ENV production

WORKDIR /usr/src/app

COPY .npmrc ./.npmrc
COPY package.json package.json
COPY package-lock.json package-lock.json

# this install command won't work!
RUN npm ci --omit=dev

COPY . .

EXPOSE 3000

CMD node index.js